config/routes.rb
Myblog::Application.routes.draw do
  root to: "entries#index"

  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in" => "sessions#new", as: "log_in"

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :feelings_and_needs, only: [:index, :create]
  resources :entries
  resources :nvc_trigger_journal_entries
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :title, :body, :user

  belongs_to :user

  validates_presence_of :title
  validates_presence_of :user_id
end

app/models/feeling.rb
class Feeling < ActiveRecord::Base
  attr_accessible :name, :header_feeling

  validates_uniqueness_of :name

  before_create :set_head
  has_many :related_feelings, class_name: 'Feeling', :foreign_key => 'header_feeling', :primary_key => 'name'

  scope :heads_only, where(head: true)

  def child_feelings
    self.related_feelings - [self]
  end

  private

  def set_head
    self.head = self.name == self.header_feeling
    self
  end
end

app/models/need.rb
class Need < ActiveRecord::Base
  attr_accessible :name, :header_need

  validates_uniqueness_of :name

  before_create :set_head
  has_many :related_needs, class_name: 'Need', :foreign_key => 'header_need', :primary_key => 'name'

  scope :heads_only, where(head: true)

  def child_needs
    self.related_needs - [self]
  end

  private

  def set_head
    self.head = self.name == self.header_need
    self
  end
end

app/models/nvc_trigger_journal_entry.rb
class NvcTriggerJournalEntry < ActiveRecord::Base
  attr_accessible :trigger_object,
    :my_feelings,
    :my_needs,
    :my_request,
    :her_his_feelings,
    :her_his_needs,
    :my_amended_request,
    :user

  belongs_to :user

  validates_presence_of :user_id

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :name, :password

  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :entries
  has_many :nvc_trigger_journal_entries

  def self.authenticate(name, password)
    find_by_name(name).try(:authenticate, password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @entry = Entry.new
  end

  def create
    if current_user
      @entry = Entry.new(params[:entry].merge(user: current_user))
      if @entry.save
        redirect_to entry_path(@entry)
      else
        render "new"
      end
    else
      redirect_to login_path, flash: "You must login to create this"
    end
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.user == current_user
      if @entry.update_attributes(params[:entry])
        redirect_to entry_path(@entry)
      else
        render "edit"
      end
    else
      redirect_to entry_path(@entry), notice: "You can't edit this"
    end
  end
end

app/controllers/feelings_and_needs_controller.rb
class FeelingsAndNeedsController < ApplicationController

  def index
    @head_feelings = Feeling.heads_only
    @head_needs = Need.heads_only
  end

  def create
    head_feeling_string = params[:head_feeling_string]
    feelings_string = params[:feelings_string]
    head_need_string = params[:head_need_string]
    needs_string = params[:needs_string]

    feelings_string.split(", ").each do |feeling|
      Feeling.create(name: feeling, header_feeling: head_feeling_string)
    end
    needs_string.split(", ").each do |need|
      logger.debug need*50
      n = Need.create(name: need, header_need: head_need_string)
      logger.debug n.errors.inspect
    end
    redirect_to feelings_and_needs_path
  end
end

app/controllers/nvc_trigger_journal_entries_controller.rb
class NvcTriggerJournalEntriesController < ApplicationController
  def index
    @nvc_trigger_entries = current_user.nvc_trigger_journal_entries
  end

  def show
    @nvc_trigger_entry = NvcTriggerJournalEntry.find(params[:id])
    if @nvc_trigger_entry.user.id != current_user.id
      redirect_to nvc_trigger_journal_entries_path, flash: "This is not your post"
    end
  end

  def new
    @nvc_trigger_entry = NvcTriggerJournalEntry.new
  end

  def create
    if current_user
      @nvc_trigger_entry = NvcTriggerJournalEntry.new(params[:nvc_trigger_journal_entry].merge(user: current_user))
      if @nvc_trigger_entry.save
        redirect_to nvc_trigger_journal_entry_path(@nvc_trigger_entry)
      else
        render "new"
      end
    else
      redirect_to login_path, flash: "You must login to create this"
    end
  end

  def edit
    @nvc_trigger_entry = NvcTriggerJournalEntry.find(params[:id])
  end

  def update
    @nvc_triger_entry = NvcTriggerJournalEntry.find(params[:id])
    if @nvc_trigger_entry.user == current_user
      if @nvc_trigger_entry.update_attributes(params[:nvc_trigger_journal_entry])
        redirect_to nvc_trigger_journal_entry_path(@nvc_trigger_entry)
      else
        render "edit"
      end
    else
      redirect_to nvc_trigger_journal_entry_path(@nvc_trigger_entry), notice: "You can't edit this"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:name], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = "No!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_form.html.haml
.change_entry
  = form_for @entry do |f|
    - if @entry.errors.any?
      - @entry.errors.full_messages.each do |msg|
        = msg

    %p
      = f.text_field :title

    %p
      = f.text_area :body

    %p
      = f.submit

app/views/entries/index.html.haml
- if current_user
  .new_entry_link
    = link_to "New Entry", new_entry_path

.entries_list
  - @entries.each do |entry|
    %p
      = link_to entry.title, entry_path(entry)

app/views/entries/show.html.haml
.entry
  %h2
    = @entry.title
  %p
    = @entry.body

app/views/feelings_and_needs/index.html.haml
.needs_list
  Needs:
  %ul.category
    - @head_needs.each do |need|
      %li.grouping
        %ul
          %li.header
            = need.name
            - need.child_needs.each do |child_need|
              %li.child
                = child_need.name


.feelings_list
  Feelings:
  %ul.category
    - @head_feelings.each do |feeling|
      %li.grouping
        %ul
          %li.header
            = feeling.name
            - feeling.child_feelings.each do |child_feeling|
              %li.child
                = child_feeling.name

.enter_needs_and_feelings
  = form_tag feelings_and_needs_path do
    %p
      = label_tag :head_need_string
      = text_field_tag :head_need_string
    %p
      = label_tag :needs_string
      = text_field_tag :needs_string
    %p
      = label_tag :head_feeling_string
      = text_field_tag :head_feeling_string
    %p
      = label_tag :feelings_string
      = text_field_tag :feelings_string
    %p
      = submit_tag "Save"

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title My Blog
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #header
      .home
        = link_to "Home", root_path 
        = link_to "NVC", nvc_trigger_journal_entries_path
      .login
        - if current_user
          = link_to "Log out", log_out_path
        - else
          = link_to "Sign up", new_user_path
          = link_to "Log in", log_in_path

    #flash
      - flash.each do |key, value|
        %div{:id => "flash#{key}"}
          = value
    = yield

app/views/nvc_trigger_journal_entries/_form.html.haml
.change_nvc_trigger_entry
  = form_for @nvc_trigger_entry do |f|
    - if @nvc_trigger_entry.errors.any?
      - @nvc_triggerentry.errors.full_messages.each do |msg|
        = msg

    %p
      = f.label :trigger_object, "Trigger observation"
      = f.text_area :trigger_object

    %p
      = f.label :my_feelings
      = f.text_field :my_feelings
    %p
      = f.label :my_needs
      = f.text_field :my_needs
    %p
      = f.label :my_request
      = f.text_area :my_request
    %p
      = f.label :her_his_feelings, "Her/His feelings"
      = f.text_field :her_his_feelings
    %p
      = f.label :her_his_needs, "Her/His needs"
      = f.text_field :her_his_needs
    %p
      = f.label :my_amended_request
      = f.text_area :my_amended_request

    %p
      = f.submit "Save"

app/views/nvc_trigger_journal_entries/edit.html.haml
= render partial: 'form'

app/views/nvc_trigger_journal_entries/index.html.haml
- if current_user
  .new_entry_link
    = link_to "New NVC Trigger Journal Entry", new_nvc_trigger_journal_entry_path

.entries_list
  - @nvc_trigger_entries.each do |nvc_entry|
    %p
      = link_to nvc_entry.trigger_object, nvc_trigger_journal_entry_path(nvc_entry)

app/views/nvc_trigger_journal_entries/new.html.haml
= render partial: 'form'

app/views/nvc_trigger_journal_entries/show.html.haml
.nvc_trigger_entry
  .entry_section
    Trigger observation:
  .entry_input
    = @nvc_trigger_entry.trigger_object

  .entry_section
    My needs:
  .entry_input
    = @nvc_trigger_entry.my_needs
  
  .entry_section
    My request:
  .entry_input
    = @nvc_trigger_entry.my_request

  .entry_section
    Her/His feelings:
  .entry_input
    = @nvc_trigger_entry.her_his_feelings

  .entry_section
    Her/His needs:
  .entry_input
    = @nvc_trigger_entry.her_his_needs

  .entry_section
    My amended request:
  .entry_input
    = @nvc_trigger_entry.my_amended_request

app/views/users/new.html.haml
#signup
  = form_for @user do |f|
    - if @user.errors.any?
      - @user.errors.full_messages.each do |msg|
        = msg

    %p
      = f.label :name
      = f.text_field :name

    %p
      = f.label :password
      = f.password_field :password

    %p
      = f.submit